### ISSUE TITLE
Sail  Quest too long?

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#12]
Ugh... I am trying to complete the sail quest so I can advance, I am in autumn  18 of the first year. The quest calls for 8 sails so you can upgrade the windmill.  I know you can't change the cost of seeds....but I have calculated you need 32-33 plots of hemp to complete that task. First off...what time line to you expect that quest to be done? First year, second year? I know it isn't a time push pack....just thinking about keeping up  advancement so people don't get bored. The only seeds that don't require watering so far is grass, (yeah I miss the blackberries lol) so you have to water all those  Vegetable  seeds to get money to buy the seeds or to eat to have energy to water so many crops.  As it is I will have to wait until mid spring or mid summer of yr 2 finish that quest.

**Comment by teagan75** [comment]
I can definitely change it so it isn't required to move on in the book. It does seem a lot of money and a lot of time.

**Comment by Ladysarajane** [comment]
Exactly...I mean it takes a lot to complete that quest and I am afraid people might be discouraged and give up the pack if they don't do some advancing. Do it like you do the medium egg and medium wool and milk quests? The quests are still there....just not required to move on.

**Comment by teagan75** [comment]
Couple disappointments today: 1. Allowing another minecolony in the nether does not work even when the config is enabled. 2. Tektopia miners do not recognize nether ores as ore. So, mining in the nether will have to be done using machines. Thinking of ways to incorporate tektopia into overworld city

Edit: A lot of the minecolonies structures are valid tektopia structures. So that would be interesting integration. I have already included a schematic for a tavern once you get to brewcraft. I am going to move this to a new issue so we can keep it open for discussion.

**Comment by Ladysarajane** [comment]
Personally I have never tried having a tektopia or minecolony in any other dimension. Tektopia citizens do have "personal space" issues in their buildings. Especially housing.

**Comment by Ladysarajane** [comment]
At the end of autumn first year....I was only able to make 2 sails in that quest.

**Comment by teagan75** [comment]
i am pushing a quick update today

**Comment by Ladysarajane** [comment]
Thank you....I want to see what is in the next chapter!!!

**Comment by teagan75** [comment]
lol. This is fixed in v).5.1_beta which is live
